name: Build docker image

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build-docker-image:
    name: Build docker image
    uses: restatedev/restate/.github/workflows/docker.yml@main
    secrets: inherit
